### ISSUE TITLE
AdMob not showing on test mode

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#111]
AdBanner (AdMob) on test mode does not showing.

When I add `SchedulerBinding.instance.addPostFrameCallback`, it works.

```
SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
  _createAnchoredBanner(context);
});
```

## Expected behavior (required)

There should be a banner like below.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/5080329/200842346-354c5dda-c79c-457e-8ecb-72e31665032d.png">

## Current behavior (required)

But the text instruction is shown like below.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/5080329/200842123-44522e89-276c-4220-92db-b9db3e0e0525.png">

## To Reproduce (required)

To reproduce, just follow exactly same as the document in 
* https://docs.flutterflow.io/settings-and-integrations/integrations/admob
* https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/adbanner

1. Just run the app as it is instructed on official document.

## Error message on console

```
Restarted application in 841ms.
[GoRouter] known full paths for routes:
[GoRouter]   => /
[GoRouter]   =>   /entry
[GoRouter]   =>   /home
[GoRouter]   =>   /profile
[GoRouter]   =>   /test
[GoRouter] known full paths for route names:
[GoRouter]   _initialize => /
[GoRouter]   entry => /entry
[GoRouter]   home => /home
[GoRouter]   profile => /profile
[GoRouter]   test => /test
[GoRouter] setting initial location /
[GoRouter] refreshing /
[GoRouter] refreshing /
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: dependOnInheritedWidgetOfExactType<MediaQuery>() or dependOnInheritedElement() was called before _FlutterFlowAdBannerState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
#0      StatefulElement.dependOnInheritedElement.<anonymous closure>
#1      StatefulElement.dependOnInheritedElement
#2      Element.dependOnInheritedWidgetOfExactType
#3      MediaQuery.of
#4      _FlutterFlowAdBannerState._createAnchoredBanner
#5      _FlutterFlowAdBannerState.initState
#6      StatefulElement._firstBuild
#7      ComponentElement.mount
#8      Element.inflateWidget
#9      MultiChildRenderObjectElement.inflateWidget
#10     MultiChildRenderObjectElement.mount
#11     Element.inflateWidget
#12     Element.updateChild
#13     SingleChildRenderObjectElement.mount
#14     Element.inflateWidget
#15     Element.updateChild
#16     SingleChildRenderObjectElement.mount
#17     Element.inflateWidget
#18     Element.updateChild
#19     SingleChildRenderObjectElement.mount
#20     Element.inflateWidget
#21     Element.updateChild
#22     ComponentElement.performRebuild
#23     StatefulElement.performRebuild
#24     Element.rebuild
#25     ComponentElement._firstBuild
#26     StatefulElement._firstBuild
#27     ComponentElement.mount
#28     Element.inflateWidget
#29     Element.updateChild
#30     ComponentElement.performRebuild
#31     Element.rebuild
#32     ComponentElement._firstBuild
#33     ComponentElement.mount
#34     Element.inflateWidget
#35     Element.updateChild
#36     ComponentElement.performRebuild
#37     Element.rebuild
#38     ComponentElement._firstBuild
#39     ComponentElement.mount
#40     Element.inflateWidget
#41     Element.updateChild
#42     SingleChildRenderObjectElement.mount
#43     Element.inflateWidget
#44     Element.updateChild
#45     ComponentElement.performRebuild
#46     Element.rebuild
#47     ComponentElement._firstBuild
#48     ComponentElement.mount
#49     Element.inflateWidget
#50     Element.updateChild
#51     ComponentElement.performRebuild
#52     Element.rebuild
#53     ComponentElement._firstBuild
#54     ComponentElement.mount
#55     Element.inflateWidget
#56     Element.updateChild
#57     ComponentElement.performRebuild
#58     Element.rebuild
#59     ComponentElement._firstBuild
#60     ComponentElement.mount
#61     Element.inflateWidget
#62     Element.updateChild
#63     ComponentElement.performRebuild
#64     Element.rebuild
#65     ComponentElement._firstBuild
#66     ComponentElement.mount
#67     Element.inflateWidget
#68     Element.updateChild
#69     ComponentElement.performRebuild
#70     Element.rebuild
#71     ComponentElement._firstBuild
#72     ComponentElement.mount
#73     Element.inflateWidget
#74     MultiChildRenderObjectElement.inflateWidget
#75     MultiChildRenderObjectElement.mount
#76     Element.inflateWidget
#77     Element.updateChild
#78     ComponentElement.performRebuild
#79     Element.rebuild
#80     ComponentElement._firstBuild
#81     ComponentElement.mount
#82     Element.inflateWidget
#83     Element.updateChild
#84     ComponentElement.performRebuild
#85     StatefulElement.performRebuild
#86     Element.rebuild
#87     ComponentElement._firstBuild
#88     StatefulElement._firstBuild
#89     ComponentElement.mount
#90     Element.inflateWidget
#91     Element.updateChild
#92     ComponentElement.performRebuild
#93     StatefulElement.performRebuild
#94     Element.rebuild
#95     ComponentElement._firstBuild
#96     StatefulElement._firstBuild
#97     ComponentElement.mount
#98     Element.inflateWidget
#99     Element.updateChild
#100    ComponentElement.performRebuild
#101    Element.rebuild
#102    ComponentElement._firstBuild
#103    ComponentElement.mount
#104    Element.inflateWidget
#105    Element.updateChild
#106    ComponentElement.performRebuild
#107    StatefulElement.performRebuild
#108    Element.rebuild
#109    ComponentElement._firstBuild
#110    StatefulElement._firstBuild
#111    ComponentElement.mount
#112    Element.inflateWidget
#113    Element.updateChild
#114    SingleChildRenderObjectElement.mount
#115    Element.inflateWidget
#116    Element.updateChild
#117    ComponentElement.performRebuild
#118    Element.rebuild
#119    ComponentElement._firstBuild
#120    ComponentElement.mount
#121    Element.inflateWidget
#122    Element.updateChild
#123    SingleChildRenderObjectElement.mount
#124    Element.inflateWidget
#125    Element.updateChild
#126    ComponentElement.performRebuild
#127    StatefulElement.performRebuild
#128    Element.rebuild
#129    ComponentElement._firstBuild
#130    StatefulElement._firstBuild
#131    ComponentElement.mount
#132    Element.inflateWidget
#133    Element.updateChild
#134    ComponentElement.performRebuild
#135    StatefulElement.performRebuild
#136    Element.rebuild
#137    ComponentElement._firstBuild
#138    StatefulElement._firstBuild
#139    ComponentElement.mount
#140    Element.inflateWidget
#141    Element.updateChild
#142    ComponentElement.performRebuild
#143    Element.rebuild
#144    ComponentElement._firstBuild
#145    ComponentElement.mount
#146    Element.inflateWidget
#147    Element.updateChild
#148    ComponentElement.performRebuild
#149    Element.rebuild
#150    ComponentElement._firstBuild
#151    ComponentElement.mount
#152    Element.inflateWidget
#153    Element.updateChild
#154    ComponentElement.performRebuild
#155    Element.rebuild
#156    ComponentElement._firstBuild
#157    ComponentElement.mount
#158    Element.inflateWidget
#159    Element.updateChild
#160    ComponentElement.performRebuild
#161    StatefulElement.performRebuild
#162    Element.rebuild
#163    ComponentElement._firstBuild
#164    StatefulElement._firstBuild
#165    ComponentElement.mount
#166    Element.inflateWidget
#167    Element.updateChild
#168    ComponentElement.performRebuild
#169    Element.rebuild
#170    ComponentElement._firstBuild
#171    ComponentElement.mount
#172    Element.inflateWidget
#173    Element.updateChild
#174    ComponentElement.performRebuild
#175    StatefulElement.performRebuild
#176    Element.rebuild
#177    ComponentElement._firstBuild
#178    StatefulElement._firstBuild
#179    ComponentElement.mount
#180    Element.inflateWidget
#181    Element.updateChild
#182    ComponentElement.performRebuild
#183    StatefulElement.performRebuild
#184    Element.rebuild
#185    ComponentElement._firstBuild
#186    StatefulElement._firstBuild
#187    ComponentElement.mount
#188    Element.inflateWidget
#189    Element.updateChild
#190    SingleChildRenderObjectElement.update
#191    Element.updateChild
#192    ComponentElement.performRebuild
#193    Element.rebuild
#194    StatelessElement.update
#195    Element.updateChild
#196    SingleChildRenderObjectElement.update
#197    Element.updateChild
#198    SingleChildRenderObjectElement.update
#199    Element.updateChild
#200    ComponentElement.performRebuild
#201    StatefulElement.performRebuild
#202    Element.rebuild
#203    StatefulElement.update
#204    Element.updateChild
#205    RenderObjectElement.updateChildren
#206    MultiChildRenderObjectElement.update
#207    Element.updateChild
#208    ComponentElement.performRebuild
#209    StatefulElement.performRebuild
#210    Element.rebuild
#211    StatefulElement.update
#212    Element.updateChild
#213    SingleChildRenderObjectElement.update
#214    Element.updateChild
#215    ComponentElement.performRebuild
#216    StatefulElement.performRebuild
#217    Element.rebuild
#218    StatefulElement.update
#219    Element.updateChild
#220    SingleChildRenderObjectElement.update
#221    Element.updateChild
#222    ComponentElement.performRebuild
#223    StatefulElement.performRebuild
#224    Element.rebuild
#225    StatefulElement.update
#226    Element.updateChild
#227    SingleChildRenderObjectElement.update
#228    Element.updateChild
#229    ComponentElement.performRebuild
#230    StatefulElement.performRebuild
#231    Element.rebuild
#232    StatefulElement.update
#233    Element.updateChild
#234    ComponentElement.performRebuild
#235    Element.rebuild
#236    StatelessElement.update
#237    Element.updateChild
#238    ComponentElement.performRebuild
#239    StatefulElement.performRebuild
#240    Element.rebuild
#241    StatefulElement.update
#242    Element.updateChild
#243    SingleChildRenderObjectElement.update
#244    Element.updateChild
#245    SingleChildRenderObjectElement.update
#246    Element.updateChild
#247    ComponentElement.performRebuild
#248    Element.rebuild
#249    ProxyElement.update
#250    _InheritedNotifierElement.update
#251    Element.updateChild
#252    SingleChildRenderObjectElement.update
#253    Element.updateChild
#254    ComponentElement.performRebuild
#255    StatefulElement.performRebuild
#256    Element.rebuild
#257    StatefulElement.update
#258    Element.updateChild
#259    ComponentElement.performRebuild
#260    Element.rebuild
#261    ProxyElement.update
#262    Element.updateChild
#263    ComponentElement.performRebuild
#264    Element.rebuild
#265    ProxyElement.update
#266    Element.updateChild
#267    ComponentElement.performRebuild
#268    StatefulElement.performRebuild
#269    Element.rebuild
#270    StatefulElement.update
#271    Element.updateChild
#272    ComponentElement.performRebuild
#273    Element.rebuild
#274    StatelessElement.update
#275    Element.updateChild
#276    ComponentElement.performRebuild
#277    Element.rebuild
#278    StatelessElement.update
#279    Element.updateChild
#280    SingleChildRenderObjectElement.update
#281    Element.updateChild
#282    ComponentElement.performRebuild
#283    Element.rebuild
#284    ProxyElement.update
#285    Element.updateChild
#286    ComponentElement.performRebuild
#287    Element.rebuild
#288    ProxyElement.update
#289    Element.updateChild
#290    ComponentElement.performRebuild
#291    StatefulElement.performRebuild
#292    Element.rebuild
#293    StatefulElement.update
#294    Element.updateChild
#295    ComponentElement.performRebuild
#296    StatefulElement.performRebuild
#297    Element.rebuild
#298    StatefulElement.update
#299    Element.updateChild
#300    ComponentElement.performRebuild
#301    StatefulElement.performRebuild
#302    Element.rebuild
#303    BuildOwner.buildScope
#304    WidgetsBinding.drawFrame
#305    RendererBinding._handlePersistentFrameCallback
#306    SchedulerBinding._invokeFrameCallback
#307    SchedulerBinding.handleDrawFrame
#308    SchedulerBinding._handleDrawFrame
#309    _invoke (dart:ui/hooks.dart:148:13)
#310    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#311    _drawFrame (dart:ui/hooks.dart:115:31)
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

## How to fix the error

* Add the code below in the `initState()` method in the `./lib/flutter_flow/flutter_flow_ad_banner.dart`.

```
SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
  _createAnchoredBanner(context);
});
```

**Comment by bulgariamitko** [comment]
@thruthesky did you try to reproduce this issue on a brand new project as well?

**Comment by thruthesky** [comment]
@bulgariamitko No, I didn't, yet.

**Comment by bulgariamitko** [comment]
It is important to try and reproduce this issue on a brand new project as well, so we know it is not an isolated issue.

**Comment by bulgariamitko** [comment]
Presented fix by the user
SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
  _createAnchoredBanner(context);
});

**Comment by asmengistu** [comment]
Thanks for the report and suggested fix @thruthesky! This should be fixed with the next deploy. Will wait to close until it's confirmed.
