### ISSUE TITLE
new failure

### ISSUE THREAD

**Issue by 978bobs** [FlutterFlow/flutterflow-issues#1381]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

here is the link for project run version:  https://app.flutterflow.io/run/vC4qk6uUqM2aakdJyEeL
it is also a publicly linked project:  https://app.flutterflow.io/project/hive-sample-app-3zux4b

fails in Test Mode worked a couple of weeks ago.
Here is the error message in chrome browser:
Uncaught (in promise) Error: Expected a value of type 'String', but got one of type 'int'
    at Object.throw_ [as throw] (dart_sdk.js:5463:11)
    at Object.castError (dart_sdk.js:5422:15)
    at Object.cast [as as] (dart_sdk.js:5745:19)
    at String.as (dart_sdk.js:46771:19)
    at setup_item_hive.ItemAdapter.new.read (setup_item_hive.dart:56:13)
    at binary_reader_impl.BinaryReaderImpl.new.read (binary_reader_impl.dart:328:24)
    at storage_backend_js.StorageBackendJs.new.decodeValue (storage_backend_js.dart:86:24)
    at MappedListIterable.new.elementAt (dart_sdk.js:24932:25)
    at ListIterator.new.moveNext (dart_sdk.js:24734:55)
    at JsIterator.next (dart_sdk.js:7500:21)
    at storage_backend_js.StorageBackendJs.new.initialize (storage_backend_js.dart:155:16)
    at initialize.next (<anonymous>)
    at dart_sdk.js:41426:33
    at _RootZone.runUnary (dart_sdk.js:41259:59)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:36462:29)
    at handleValueCallback (dart_sdk.js:37033:49)
    at _Future._propagateToListeners (dart_sdk.js:37071:17)
    at [_completeWithValue] (dart_sdk.js:36906:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36940:35)
    at Object._microtaskLoop (dart_sdk.js:41734:13)
    at _startMicrotaskLoop (dart_sdk.js:41740:13)
    at dart_sdk.js:37296:9

### Expected Behavior

this application worked for weeks on end.  should show a user interface to create a list of item data and then be able to CRUD it.

### Steps to Reproduce

1. open my app. and run in test mode.
2. you will see the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kMrq05NgrsNY1qX6avlR/TgWOUs7ROYN0+ptcxE8KOPaPOw+Ps/BM0RuTum9dGNiIlmJgWoW3PyNjoTxCfY4Jk+tfrY71qp+EgrdXkaRVZSwFJWgdXRCJ5pQIH66yqevoxBRJtptcVYC3V73P96tXh7fHr7BOW4wD6/LZO4=

### Context

I am working to use Flutter Hive db without using any features associated with FIREBASE or SUPABASE.  I got this app working a couple weeks back.  Now I am getting this error.  I have derived other versions of this app so I can work to improve on it and those derived versions are getting this error as well.  At first I thought it was my recent work, and then I went back and tried this originally working app.  I know that this app was working a couple days ago because I recently shared it with another user and they confirmed it worked.

### Visual documentation

![error flutterflow 08302023](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/5a85d30c-ef36-43ca-88c2-5a7a512c4bbf)
![Screenshot 8-30-2023 at 12 08 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/f8fdd582-96a3-4221-9a2e-ea49a333dc00)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web
- Browser name and version: chrome Version 116.0.5845.111 (Official Build) (64-bit)
- Operating system and version affected: Edition	Windows 11 Pro
Version	22H2
Installed on	‎1/‎28/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0
```

**Comment by hariprasadms** [comment]
Hi @978bobs - I can clone your project and run debug run. it works fine. Is this working for you now ?

<img width="1453" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ed5ab4d8-57f3-4c4a-8f52-73a3f8657fc5">

**Comment by 978bobs** [comment]
Ah ha!  Yes I can.  I turns out that in debugging I need to remember that if I change anything about the data structure, I need to delete from the data-store in the browser sandbox!
Thank you Hari,
Bob
