### ISSUE TITLE
Launch URL Action Fails to open specified URL

### ISSUE THREAD

**Issue by medatlas** [FlutterFlow/flutterflow-issues#1492]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I followed this tutorial to add Launch URL action to a button but while testing, the URL specified in the action does not open and see the error below in Chrome browser console. This error is not specific to any URL.

Uncaught Could not launch https://flutterflow.io: Error: JavaScript cannot open windows automatically
    at Object.f (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:3003:3)
    at https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:28258:9
    at aYx.a (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:4303:62)
    at aYx.$2 (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:37887:14)
    at aXn.$2 (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:37884:16)
    at aUS.akM (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:38837:36)
    at aUS.UE (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:38839:23)
    at iI.q9 (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:38155:18)
    at aRe.$0 (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:38299:37)
    at Object.U8 (https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/build_outputs/kotiz-chatbot-ui-3ne3pv/web/RXopb4CWbLnhybMT0rud/main.dart.js:4426:78)

### Expected Behavior

The URL should open.

### Steps to Reproduce

1- Add Launch URL action to a button
2- Launch the App in Chrome
3- Expected to see the URL open
4- The URL does't open and shows an error in the browser console

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CjcmB249Jn7xa1br+Kfpv9WA5KVw/RYEzl9V9bw8dJ5PMC+wIZ/f7XFRuTde0dH9lemL9nn010P/emvHfU/c3PkitR4h+yLpXEzzJXkW5R6rUDLWwP25/DcFbfGK015ikkSRTAMliL0IX3F+YHOjIaHTvQ5DxNVUdL/iiWJOK2SrDX1iXc2URm05KZDPz

### Context

I am trying to open an external webpage using Launch URL action.

### Visual documentation

<img width="1431" alt="Screenshot 2023-09-20 at 4 16 19 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/36462942/a9b5a692-6aaf-4bdb-9055-004a13005dd4">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: MacOS
- Browser name and version: Chrome 116.0.5845.140
- Operating system and version affected: Ventura 13.5
```

**Comment by victoriahuang1** [comment]
Hi @medatlas , thank you for the report. Please add your bug report code, so that we are able to take a look at your project.

See step 8 here for instructions on how to generate the bug report code: https://docs.flutterflow.io/troubleshooting/submit-bug-reports

**Comment by medatlas** [comment]
Hi @victoriahuang1 I added the bug report code.

**Comment by SameerShahzad99** [comment]
It looks like the bug report code that you have shared is not for a blank project with the issue reproduced, but I tested this action on a blank project and it did not get reproduced!
