### ISSUE TITLE
CheckBoxGroup initialized to null rather than empty list when nothing selected

### ISSUE THREAD

**Issue by TomJFox** [FlutterFlow/flutterflow-issues#1589]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a CheckBoxGroup to allow options to be selected, I am getting a null exception thrown when using the Number of Items option as part of a conditional action when I have not selected anything.
I created a project from scratch to demonstrate the issue.  Button press should bring up a SnackBar with 'Options Found' or 'No Options Found' which is dependent on the conditional action checking Number of Items in the CheckBoxGroup in Widget State.  When nothing is selected a null exception is thrown (see Additional Info below).  When something is selected, the 'Options Found' SnackBar shows.  If that select is then removed, the 'No Options Found' Snackbar is shown.

### Expected Behavior

I would expect the CheckBoxGroup to initialise to an empty list rather than null when nothing is selected.  This would allow Number of Items to be queried and return zero as it does when all options are checked and then checks are removed.

### Steps to Reproduce

Create Page
Add CheckBox Group and Button
Under Actions of Button create a conditional action using Number of Items for the CheckBoxGroup.  For instance checking if it is greater than zero.
Make sure nothing is selected and press the button.  Null Error is thrown.
Select something and press the button.  SnackBar is shown.
Remove all selections and press the button.  SnackBar is shown.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elcr135VNj7xZ1s7fbfkxhiYRKUs7U403m+0aaAwbF4zkBKQAPejxP2FoUtfiTAk7L2akgnwK/trShtnMA+UpAE6tbIhd1pB2VgmWfF6RaYuVDamKXX9RJ9FJJVyg1Kug2yNDCMlfclot11yUGeuUVh7DNpDPClY3HPn8JqHUn12qQ0SLb3kNh1JWeC/v

### Context

In another project I am attempting to use three CheckBoxGroups to allow the user to pick items from 3 groups.  I then need to ensure they have selected at least one item from any of the 3 groups.  Handling the null values is preventing me from using Code expressions to simply combine the 3 lists into a single list.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/106626912/9bb33663-9eca-4a49-8cf4-ece873cea3cf

### Additional Info

Error message thrown when pressing button with nothing selected:

```
Uncaught (in promise) Error: Unexpected null value.
    at Object.throw_ [as throw] (dart_sdk.js:5463:11)
    at Object.nullCheck (dart_sdk.js:5787:30)
    at home_page_widget._HomePageWidgetState.new.<anonymous> (home_page_widget.dart:83:58)
    at Generator.next (<anonymous>)
    at runBody (dart_sdk.js:41451:34)
    at Object._async [as async] (dart_sdk.js:41483:7)
    at home_page_widget.dart:82:28
    at flutter_flow_widgets._FFButtonWidgetState.new.<anonymous> (flutter_flow_widgets.dart:105:32)
    at Generator.next (<anonymous>)
    at runBody (dart_sdk.js:41451:34)
    at Object._async [as async] (dart_sdk.js:41483:7)
    at flutter_flow_widgets.dart:99:15
    at ink_well._InkResponseState.new.handleTap (ink_well.dart:1154:21)
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:275:24)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:654:11)
    at [_checkUp] (tap.dart:311:5)
    at tap.TapGestureRecognizer.new.acceptGesture (tap.dart:281:7)
    at arena.GestureArenaManager.new.sweep (arena.dart:167:12)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:469:20)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:445:14)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:331:11)
    at [_handlePointerEventImmediately] (binding.dart:400:7)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:363:5)
    at [_flushPointerEventQueue] (binding.dart:320:7)
    at [_handlePointerDataPacket] (binding.dart:293:9)
    at Object.invoke1 (dart_sdk.js:207087:7)
    at _engine.EnginePlatformDispatcher.new.invokeOnPointerDataPacket (dart_sdk.js:177005:15)
    at [_onPointerData] (dart_sdk.js:178303:49)
    at dart_sdk.js:178901:30
    at dart_sdk.js:178841:9
    at loggedHandler (dart_sdk.js:178480:11)
    at Object._checkAndCall (dart_sdk.js:5666:16)
    at Object.dcall (dart_sdk.js:5671:17)
    at ret (dart_sdk.js:63548:21)
```

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: x86
- Browser name and version: Google Chrome Version 117.0.5938.132 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @TomJFox, Thanks for submitting the issue. I have tested above steps. I can see it is working as expected. Nothing changed in your project, its all the same configuration but I just added on selected action to show the number of option selected. Is this resolved for you now? If that is the case let me know I can close the issue. Thanks

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a488e7e4-3dd5-4c52-a4a8-ca1e651fef88

**Comment by TomJFox** [comment]
@hariprasadms please re-open this is still failing.  

Two things have changed in your version.  

First, you have Option 1 set by default.  I have no options set by default. This is very important.  I do not want a default option set.

Second, you are displaying Num Iist Items on the page, I am not (and do not want to do this!).

When no option is set by default, then the group list should be initialised to an empty list [] rather than null.

This works if you add and remove options on the screen, but I need it to work when the page is loaded with a group with no options selected.

Thanks
