### ISSUE TITLE
assets_audio_player's "showNotification: true" make app crash on android

### ISSUE THREAD

**Issue by Gintasz** [FlutterFlow/flutterflow-issues#1829]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So I have custom audio player widget, wanting to play audio in background... If I have `showNotification: true`, it works on iOS but on Android it gives crash.

```
E/AndroidRuntime(18053): FATAL EXCEPTION: main
E/AndroidRuntime(18053): Process: com.appside.mybe, PID: 18053
E/AndroidRuntime(18053): java.lang.NoSuchFieldError: No static field exo_icon_previous of type I in class Lcom/github/florent37/assets_audio_player/R$drawable; or its superclasses (declaration of 'com.github.florent37.assets_audio_player.R$drawable' appears in /data/app/com.appside.mybe-7GDPqMEzUmlYrwAM4rnvyA==/base.apk!classes3.dex)
E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.getPrevIcon(NotificationService.kt:179)
E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.displayNotification(NotificationService.kt:242)
E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.access$displayNotification(NotificationService.kt:29)
E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService$displayNotification$1.invokeSuspend(NotificationService.kt:143)
E/AndroidRuntime(18053): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(18053): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(18053): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(18053): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(18053): 	at android.os.Looper.loop(Looper.java:241)
E/AndroidRuntime(18053): 	at android.app.ActivityThread.main(ActivityThread.java:7582)
E/AndroidRuntime(18053): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(18053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime(18053): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@44342c3, Dispatchers.Main]
I/Process (18053): Sending signal. PID: 18053 SIG: 9
```

Although downloaded from FF app source pubspec.yaml references `assets_audio_player: 3.0.6` but on pub.dev I see there is 3.1.1 version. I tried updating, no change.

### Expected Behavior

`showNotification: true` shall work on Android & iOS

### Steps to Reproduce

Here is the widget I'm using to play audio:
```
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:flutter/foundation.dart';
import 'package:assets_audio_player/assets_audio_player.dart';
import 'dart:math';
import 'dart:io';
import 'package:flutter/foundation.dart';

class AudioSliderPlayer extends StatefulWidget {
  final double? width;
  final double? height;
  final String audioUrl;
  final String title;
  final String author;
  final String imageUrl;
  final bool isPlaying;

  AudioSliderPlayer({
    Key? key,
    this.width,
    this.height,
    required this.audioUrl,
    required this.title,
    required this.author,
    required this.imageUrl,
    this.isPlaying = false,
  }) : super(key: key);

  @override
  _AudioSliderPlayerState createState() => _AudioSliderPlayerState();
}

class _AudioSliderPlayerState extends State<AudioSliderPlayer> {
  AssetsAudioPlayer? _assetsAudioPlayer;
  Duration _totalDuration = Duration(seconds: 0);
  Duration _currentPosition = Duration(seconds: 0);

  bool _isSliding = false;
  bool _isDisposed = false;

  @override
  void initState() {
    super.initState();
    _initAudioPlayer();
  }

  _initAudioPlayer() {
    _assetsAudioPlayer = AssetsAudioPlayer.withId("grotuvas");

    Audio audio = Audio.network(widget.audioUrl);
    audio.updateMetas(
      title: widget.title,
      artist: widget.author,
      image: MetasImage.network(widget.imageUrl),
    );

    _assetsAudioPlayer!.open(
      audio,
      autoStart: widget.isPlaying,
      showNotification: !kIsWeb &&
          Platform.isIOS, // on Android, showNotification=true makes app crash
      playInBackground: PlayInBackground.enabled,
    );

    _assetsAudioPlayer!.onReadyToPlay.listen((audio) {
      setState(() {
        if (widget.isPlaying &&
            !_assetsAudioPlayer!.isPlaying.value &&
            !_isDisposed) {
          _assetsAudioPlayer!.play();
        }
        _totalDuration = audio?.duration ?? const Duration();
      });
    });

    _assetsAudioPlayer!.currentPosition.listen((position) {
      if (!_isSliding) {
        setState(() {
          _currentPosition = position;
        });
      }
      FFAppState().playerPositionSecs = position.inSeconds;
      if (position.inSeconds == _totalDuration.inSeconds) {
        _assetsAudioPlayer!.pause();
        _assetsAudioPlayer!.seek(Duration(seconds: 0));
      }
    });
  }

  @override
  void didUpdateWidget(AudioSliderPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (_isDisposed) return;

    if (oldWidget.isPlaying != widget.isPlaying) {
      if (widget.isPlaying) {
        _assetsAudioPlayer!.play();
      } else {
        _assetsAudioPlayer!.pause();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Slider(
          activeColor: Colors.white,
          inactiveColor: Colors.white,
          min: 0,
          max: _totalDuration.inMilliseconds.toDouble(),
          value: _currentPosition.inMilliseconds.toDouble(),
          onChangeStart: (startValue) {
            _isSliding = true;
          },
          onChanged: (newValue) {
            setState(() {
              _currentPosition = Duration(milliseconds: newValue.toInt());
            });
          },
          onChangeEnd: (endValue) {
            _isSliding = false;
            _assetsAudioPlayer!.seek(_currentPosition);
          },
        ),
      ],
    );
  }

  @override
  void dispose() {
    if (_assetsAudioPlayer != null && _assetsAudioPlayer!.isPlaying.value) {
      _assetsAudioPlayer!.stop();
    }
    _assetsAudioPlayer!.dispose();
    _isDisposed = true;
    super.dispose();
  }
}
```

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

E/AndroidRuntime(18053): FATAL EXCEPTION: main E/AndroidRuntime(18053): Process: com.appside.mybe, PID: 18053 E/AndroidRuntime(18053): java.lang.NoSuchFieldError: No static field exo_icon_previous of type I in class Lcom/github/florent37/assets_audio_player/R$drawable; or its superclasses (declaration of 'com.github.florent37.assets_audio_player.R$drawable' appears in /data/app/com.appside.mybe-7GDPqMEzUmlYrwAM4rnvyA==/base.apk!classes3.dex) E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.getPrevIcon(NotificationService.kt:179) E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.displayNotification(NotificationService.kt:242) E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService.access$displayNotification(NotificationService.kt:29) E/AndroidRuntime(18053): 	at com.github.florent37.assets_audio_player.notification.NotificationService$displayNotification$1.invokeSuspend(NotificationService.kt:143) E/AndroidRuntime(18053): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) E/AndroidRuntime(18053): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) E/AndroidRuntime(18053): 	at android.os.Handler.handleCallback(Handler.java:883) E/AndroidRuntime(18053): 	at android.os.Handler.dispatchMessage(Handler.java:100) E/AndroidRuntime(18053): 	at android.os.Looper.loop(Looper.java:241) E/AndroidRuntime(18053): 	at android.app.ActivityThread.main(ActivityThread.java:7582) E/AndroidRuntime(18053): 	at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(18053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) E/AndroidRuntime(18053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) E/AndroidRuntime(18053): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@44342c3, Dispatchers.Main] I/Process (18053): Sending signal. PID: 18053 SIG: 9

### Context

making app that plays audio in background

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released November 11, 2023, Flutter version is 3.13.7
- Platform: android
- Browser name and version: -
- Operating system and version affected:  android
```

**Comment by SameerShahzad99** [comment]
@Gintasz This issue seems to be project specific, as you are using custom widget, please reach out to the support team for such cases!
