### ISSUE TITLE
PageView within ListView scroll controller

### ISSUE THREAD

**Issue by anthonygoslar** [FlutterFlow/flutterflow-issues#184]
The nested PageView within the ListView scroll controller issue has been around for some time. Recently you pushed an error which has now broken my project. I wanted to share my fix for this issue:

Add a map for the PageScroller using the ListView index as the key, and then assign it to the PageView so that each PageController has a unique name. The example is below.

1. Declare the map below the other page controllers. i.e.
```
PageController? pageViewController1;
PageController? pageViewController2;
# Add this:
var pageViewControllerMap = {};
```

2. Swap out the old controllers with the dictionary using the listview index as the key. i.e.
```
# change this
controller: pageViewController2 ??=
# to this
controller: pageViewControllerMap[listViewIndex] ??=
```

Now the nested pages will have their own scroll controllers and the indicators work properly.

**Comment by anthonygoslar** [comment]
Thanks @hariprasadms 

When I'm using FlutterFlow, I'm now getting this error
![image](https://user-images.githubusercontent.com/30745006/205109174-f6dd5c7f-fa8a-4845-8a3b-84f39b6e2a97.png)

I've had issues when placing a PageView inside of a ListView. The issue is that the page view indicators don't work when scrolling the images horizontally. When debugging, the bug has been with the ScrollController. It's not a bug since it's an exception thrown by the flutter (exception raised below)

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:196:41)
#4      _DealsWidgetState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:marula_hill_travel/deals/deals_widget.dart:522:78)
#5      SmoothIndicator._onTap (package:smooth_page_indicator/src/smooth_page_indicator.dart:133:23)
#6      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:624:57)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:624:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#19     _invoke1 (dart:ui/hooks.dart:167:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 2 frames from class _AssertionError)
Handler: "onTapUp"
Recognizer: TapGestureRecognizer#6b3b0
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(195.4, 266.0)
  finalLocalPosition: Offset(33.7, 8.0)
  button: 1
  sent tap down
====================================================================================================
```

The fix I'm proposing is the solve the exception raised above.

**Comment by wenkaifan0720** [comment]
Hi @anthonygoslar. We are aware of this issue and that is why we recently pushed an update that raises this project error. Your fix should work and is the current implementation for  `Checkbox` widget. Could you try the suggested solution (making a component) and see if it works?
I think we will later downgrade the error to a warning and use this `Map` fix for those widgets that has a state variable/controller.

**Comment by anthonygoslar** [comment]
Thanks @wenkaifan0720. I'll give it a try.

**Comment by agreaves** [comment]
Hi all! I'm going to close this issue due to inactivity (as we have an acceptable proposed solution). If it is still ongoing, please let me know and I can re-open!
