### ISSUE TITLE
stuck at Test Mode

### ISSUE THREAD

**Issue by leizhao3** [FlutterFlow/flutterflow-issues#1893]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Stuck at Test Mode over 10-min. Cannot get it unblocked.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19180265/16608bbf-c571-4486-b1b5-85116ec97b93)

### Expected Behavior

Need to able to enter test mode.

### Steps to Reproduce

Not sure how to reproduce at this point.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc7lvJVgobxA1pDpbfpvhmUUQ216TL07ttYbZxUjIuPtBJh/OeLRYVVoXdSlTGlhHFegnnseptb5vfH9JvACBxyWRodzz80NFArzXXq8R4TRPbuaQ2hCAfFMJlCu07WNqxFTAM5oV2Qd3GWYPtmvEy3cJ5+/Zwh9f6PHaOI=

### Context

I'm not able to enter the test mode to test my app.

### Visual documentation

Image of Test Mode Loading Page: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19180265/9002cc36-a615-479a-930d-71eff7aed8d2)

### Additional Info

Log File, generated by `Right Click` -> `Inspection` -> `Console`. 

```
Failed to load resource: net::ERR_TIMED_OUT

[storage.googleapis.com/flutterflowdev.appspot.com/projects/lottie-storage-fgjwm7/assets/pwgc43ulpwzq/testMode_Loading_2.json:1](http://storage.googleapis.com/flutterflowdev.appspot.com/projects/lottie-storage-fgjwm7/assets/pwgc43ulpwzq/testMode_Loading_2.json:1)

Failed to load resource: net::ERR_TIMED_OUT

[storage.googleapis.com/flutterflowdev.appspot.com/projects/lottie-storage-fgjwm7/assets/pwgc43ulpwzq/testMode_Loading_2.json:1](http://storage.googleapis.com/flutterflowdev.appspot.com/projects/lottie-storage-fgjwm7/assets/pwgc43ulpwzq/testMode_Loading_2.json:1)

Failed to load resource: net::ERR_TIMED_OUT

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/dart_sdk.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/dart_sdk.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "dart_sdk", needed by: main_module.bootstrap, web_entrypoint.dart, packages/sync_mind/auth/firebase_auth/firebase_auth_manager.dart, web_plugin_registrant.dart, packages/flutter_web_plugins/src/plugin_registry.dart, packages/app_links/app_links_web.dart, packages/cloud_firestore_web/src/write_batch_web.dart, packages/firebase_auth_web/src/firebase_auth_web_recaptcha_verifier_factory.dart, packages/firebase_core_web/firebase_core_web.dart, packages/firebase_performance_web/firebase_performance_web.dart, packages/google_sign_in_web/google_sign_in_web.dart, packages/shared_preferences_web/shared_preferences_web.dart, packages/sign_in_with_apple_web/sign_in_with_apple_web.dart, packages/url_launcher_web/url_launcher_web.dart, packages/flutter/src/foundation/debug.dart, packages/flutter/src/services/binary_messenger.dart, packages/google_identity_services_web/src/js_loader.dart, packages/google_sign_in_platform_interface/src/utils.dart, packages/google_sign_in_platform_interface/src/types.dart, packages/google_sign_in_web/src/gis_client.dart, packages/flutter/src/services/text_editing_delta.dart, packages/firebase_performance_web/src/interop/performance.dart, packages/firebase_core_web/src/interop/app_interop.dart, packages/firebase_performance_platform_interface/src/method_channel/method_channel_http_metric.dart, packages/firebase_performance_web/src/trace.dart, packages/firebase_auth_platform_interface/src/types.dart, packages/firebase_auth_web/src/interop/auth_interop.dart, packages/firebase_auth_platform_interface/src/firebase_auth_exception.dart, packages/firebase_auth_web/src/interop/multi_factor.dart, packages/firebase_auth_platform_interface/src/action_code_info.dart, packages/firebase_auth_platform_interface/src/additional_user_info.dart, packages/firebase_auth_platform_interface/src/id_token_result.dart, packages/firebase_auth_platform_interface/src/providers/saml_auth.dart, packages/firebase_auth_platform_interface/src/auth_credential.dart, packages/firebase_auth_web/src/interop/utils/utils.dart, packages/firebase_auth_platform_interface/src/action_code_settings.dart, packages/app_links_platform_interface/src/method_channel_app_links.dart, packages/shared_preferences_platform_interface/method_channel_shared_preferences.dart, packages/firebase_core_platform_interface/src/pigeon/mocks.dart, packages/sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart, packages/sign_in_with_apple_platform_interface/exceptions.dart, packages/url_launcher_platform_interface/method_channel_url_launcher.dart, packages/url_launcher_web/src/link.dart, packages/flutter/src/widgets/unique_widget.dart, packages/url_launcher_platform_interface/link.dart, packages/url_launcher_platform_interface/src/types.dart, packages/cloud_firestore_web/src/internals.dart, packages/cloud_firestore_platform_interface/src/platform_interface/utils/load_bundle_task_state.dart, packages/cloud_firestore_platform_interface/src/server_timestamp_behavior.dart, packages/cloud_firestore_platform_interface/src/set_options.dart, packages/cloud_firestore_platform_interface/src/platform_interface/platform_interface_aggregate_query_snapshot.dart, packages/collection/src/equality.dart, packages/cloud_firestore_platform_interface/src/get_options.dart, packages/cloud_firestore_platform_interface/src/source.dart, packages/cloud_firestore_platform_interface/src/internal/pointer.dart, packages/firebase_core_web/src/interop/utils/utils.dart, packages/cloud_firestore_platform_interface/src/timestamp.dart, packages/cloud_firestore_platform_interface/src/geo_point.dart, packages/cloud_firestore_platform_interface/src/blob.dart, packages/cloud_firestore_platform_interface/src/snapshot_metadata.dart, packages/cloud_firestore_platform_interface/src/field_path.dart, packages/cloud_firestore_platform_interface/src/platform_interface/platform_interface_field_value.dart, packages/firebase_core_web/src/interop/utils/js.dart, packages/cloud_firestore_platform_interface/src/load_bundle_task_state.dart, packages/cloud_firestore_platform_interface/src/platform_interface/platform_interface_load_bundle_task.dart, packages/cloud_firestore_platform_interface/src/settings.dart, packages/flutter/src/foundation/change_notifier.dart, packages/firebase_auth/firebase_auth.dart, packages/sync_mind/auth/base_auth_user_provider.dart, packages/flutter/src/material/time.dart, packages/sync_mind/auth/firebase_auth/email_auth.dart, packages/sync_mind/auth/firebase_auth/anonymous_auth.dart, packages/sync_mind/auth/firebase_auth/apple_auth.dart, packages/sync_mind/auth/firebase_auth/google_auth.dart, packages/sync_mind/auth/firebase_auth/github_auth.dart, packages/sync_mind/auth/firebase_auth/jwt_token_auth.dart, packages/sync_mind/auth/firebase_auth/firebase_user_provider.dart, packages/sync_mind/auth/auth_manager.dart, packages/cloud_firestore/cloud_firestore.dart, packages/flutter/src/material/date.dart, packages/sync_mind/flutter_flow/lat_lng.dart, http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter/src/material/icons.dart.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter/src/material/icons.dart.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "packages/flutter/src/material/icons.dart", needed by: packages/sync_mind/auth/firebase_auth/firebase_auth_manager.dart, packages/flutter/src/material/time.dart, packages/expandable/expandable.dart, packages/octo_image/src/progress_indicators.dart, packages/flutter/src/material/text_selection_toolbar.dart

http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter_localizations/src/material_localizations.dart.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter_localizations/src/material_localizations.dart.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "packages/flutter_localizations/src/material_localizations.dart", needed by: packages/sync_mind/auth/firebase_auth/firebase_auth_manager.dart

http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter_localizations/src/l10n/generated_cupertino_localizations.dart.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/flutter_localizations/src/l10n/generated_cupertino_localizations.dart.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "packages/flutter_localizations/src/l10n/generated_cupertino_localizations.dart", needed by: packages/sync_mind/auth/firebase_auth/firebase_auth_manager.dart

http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/vector_math/vector_math_64.dart.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/vector_math/vector_math_64.dart.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "packages/vector_math/vector_math_64.dart", needed by: packages/flutter/src/services/text_editing_delta.dart, packages/flutter/src/widgets/unique_widget.dart, packages/flutter/src/material/time.dart, packages/sync_mind/flutter_flow/flutter_flow_animations.dart, packages/flutter_animate/src/effects/visibility_effect.dart, packages/flutter/src/gestures/recognizer.dart, packages/flutter/src/gestures/events.dart, packages/flutter/src/painting/gradient.dart, packages/flutter/src/gestures/monodrag.dart, packages/flutter/src/painting/matrix_utils.dart, packages/flutter/src/semantics/semantics.dart, packages/flutter/src/gestures/hit_test.dart, packages/flutter/src/gestures/scale.dart, packages/flutter/src/gestures/multitap.dart, packages/flutter/src/gestures/pointer_router.dart, packages/flutter_test/src/test_text_input_key_handler.dart, packages/font_awesome_flutter/src/fa_icon.dart

http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)

[storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/google_fonts/src/google_fonts_base.dart.js:1](http://storage.googleapis.com/flutterflow-prod-hosting/debugger-cache/1700271855/packages/google_fonts/src/google_fonts_base.dart.js:1)

Failed to load resource: net::ERR_TIMED_OUT

require.js:143 Uncaught Error: Script error for "packages/google_fonts/src/google_fonts_base.dart", needed by: packages/sync_mind/flutter_flow/flutter_flow_theme.dart

http://requirejs.org/docs/errors.html#scripterror

at makeError (require.js:168:17)

at HTMLScriptElement.onScriptError (require.js:1738:36)
```

### Environment

```markdown
- FlutterFlow version: v4.0 Flutter 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.159 
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment]
Hi @leizhao3. Is this still happening to you? I can run test mode with the snapshot you provided:
![Uploading iScreen Shoter - Google Chrome - 231123161054.jpg…]()

**Comment by devjones** [comment]
I have experienced this multiple times on projects with no bugs.  It brings development to a halt and one of my biggest pain points.

**Comment by devjones** [comment]
@wenkaifan0720 I don't have a bug report code as this issue only appears in test mode and I don't know how to generate a bug report code on a test run.

Here is the url of a test run right now that has been running for 13 minutes and counting today (~10am EST)
https://app.flutterflow.io/debug/MMfjyRi8O67UWaWvOPrT

Here is another url from last week where the test mode never resolved:
https://app.flutterflow.io/debug/DWZUChPGhPOGsVBdP4AC

This issue has been happening fairly regularly typically in the mornings Eastern time.  I rarely have issues after 12pm Eastern time.

I suspect this is an issue of compute resource allocation, not a code bug on my end or FlutterFlow.  Is there a spike in test runs in the mornings.  Perhaps your team can log how many test runs fail to resolve, and at what times, to identify trends and debug the core issue.

**Comment by devjones** [comment]
My workaround right now is to download the code, and compile from my local machine.  The app runs on my local machine when i do this. This is only possible because i'm on the pro plan and can download code. I'm guessing free tier users simply get stuck.

**Comment by wenkaifan0720** [comment]
@devjones. We do log test mode stats and are aware of the availability issue of firebase at different location/time. There is an ongoing effort for making the test mode experience smoother (and also for local debugging). I'll close this issue for now.

**Comment by ishak-lm** [comment]
@wenkaifan0720 Got the same issue again...

**Comment by lemmen6** [comment]
Big issue last couple of days. Almost unworkable. Would love to have a solution or you to reopen ticket.
