### ISSUE TITLE
Local run - infinity loading and never run

### ISSUE THREAD

**Issue by JustUserHere** [FlutterFlow/flutterflow-issues#2486]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i'm trying to run local run - infinity waiting and no result, no errors.

### Expected Behavior

looking forward to start using local run

### Steps to Reproduce

1. start local run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsYt2m+FF7rruYO9WimU4HFAhaq00rdoacxAgfa74E4kIfcmlYhBvOPKzaHx6BWeZuEkzzM7FjuPXUfEpNRaZf4BizcxIchPPbGagaLaVPaqoeXN5EdhYIWnH4Z2jviR5LtteW1I/1GbzB9zIbz6Cf9qOYwx5e6fDbOY=

### Context

want to start using local runs

### Visual documentation

![Снимок экрана 2024-03-10 в 00 15 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f849e32d-6515-43a2-9f56-6727cbbf529c/95076775-75d5-4c40-90e4-fc05569b2db7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mODQ5ZTMyZC02NTE1LTQzYTItOWY1Ni02NzI3Y2JiZjUyOWMvOTUwNzY3NzUtNzVkNS00YzQwLTkwZTQtZmMwNTU2OWIyZGI3IiwiaWF0IjoxNzEwMDcyMTUwLCJleHAiOjMzMjgwNjMyMTUwfQ.LsFKHKidZNTU6jL2agJ9xV2m05XTQ-jiY_WJF9PxUgU "=1556x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: mac
- Browser name and version: mac app
- Operating system and version affected: mac
```

**Comment by hariprasadms** [comment]
Hi @JustUserHere - Thanks for submitting the issue. You should more details about run log information. Flutter Doctor result and etc. These details are essential to debug FlutterFlow runner issue. Thanks

**Comment by JustUserHere** [comment]
Hello @takashiff @hariprasadms !

log information is empty (however screenshot in attachment)
Flutter doctor check outcome screenshot in attachment
and third screenshot - " Outdated version running "  - outdated version of what? And how get latest? :)

<img width="806" alt="Снимок экрана 2024-03-11 в 00 58 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/e8ea2195-869e-431d-a419-e6da7356aef4">
<img width="836" alt="Снимок экрана 2024-03-11 в 00 54 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/49586e86-712a-433a-b349-9a2d1f345714">
<img width="401" alt="Снимок экрана 2024-03-11 в 00 53 56" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/e8fa9a7e-9085-41c3-bb2f-83f42a6c1e79">
<img width="906" alt="Снимок экрана 2024-03-11 в 01 00 05" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/3502707b-4a79-476c-8cb6-ee9df4af2f23">

**Comment by takashiff** [comment]
Hi @JustUserHere, 'Outdated version running' means that the latest version of your project is not currently running. I suspect that the issues regarding Local Run may be due to your Flutter setup. I would advise resolving all of the issues in `flutter doctor` and seeing whether the issues still persist afterwards. Thanks

**Comment by JustUserHere** [comment]
@takashiff 
Hello.
Project running well outside ff local run. Please try to run local run for my project by yourself

**Comment by sbis04** [comment]
Looks like this is specifically happening while running on an iOS device. So, currently if the loading indicator is shown, it means that `pod install` step is happening in the background (which might take quite a significant time depending on the project requirements). I know it's a bit confusing currently because of the absence of the logs, but we are adding logs for it in the next update.

One more thing, @JustUserHere can you please open the Local Run config dialog, go to the "Setup Flutter" step, continue to the Flutter Doctor and copy-paste the doctor output here? (there's a button to copy doctor output)

**Comment by sbis04** [comment]
Ohh, yes I noticed the CocoaPods issue as well (reported in Flutter Doctor output), I think that's the issue why it might be stuck. Can you show what's the output of `which pod` command from terminal?

**Comment by JustUserHere** [comment]
@sbis04 
here it is. What is the path forward on this issue? Thanks!
<img width="335" alt="Снимок экрана 2024-03-13 в 21 13 03" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/0befbd99-4359-4333-89d9-fe0dc1d52e00">

**Comment by sbis04** [comment]
Okay. Seems like the CocoaPods are installed on your system in a different way, so that path is different. Currently, we support CocoaPods path `/opt/homebrew/bin` (installed with `brew`) and `/usr/local/bin` (when installed with `gem`, but that could be different installation procedures). I would suggest you, try installing CocoaPods with brew once and try: 

```sh
brew install cocoapods
```

Let me know how that goes.

**Comment by JustUserHere** [comment]
@sbis04 
Hello!
just FYI: it was not enough just to install cocoapods through brew. First it have to be uninstalled "sudo gem uninstall cocoapods"

now it is starting, but have 2 issues:
1. Hot reload and reload - nothing happening  when I'm pressing these buttons in FF. At the same time command directly to console resulting to reload.
2. Errors coming that assets not available (runs outside of FF do not resulting to this issue)
`Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_app_check: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
Downloading dependencies
Installing AppAuth (1.7.3)
Installing AppCheckCore (10.18.1)
Installing BoringSSL-GRPC (0.0.24)
Installing DKImagePickerController (4.3.4)
Installing DKPhotoGallery (0.0.17)
Installing FMDB (2.7.9)
Installing Firebase (10.22.0)
Installing FirebaseABTesting (10.22.0)
Installing FirebaseAnalytics (10.22.0)
Installing FirebaseAppCheck (10.22.0)
Installing FirebaseAppCheckInterop (10.22.0)
Installing FirebaseAuth (10.22.0)
Installing FirebaseAuthInterop (10.22.0)
Installing FirebaseCore (10.22.0)
Installing FirebaseCoreExtension (10.22.0)
Installing FirebaseCoreInternal (10.22.0)
Installing FirebaseDynamicLinks (10.22.0)
Installing FirebaseFirestore (10.22.0)
Installing FirebaseFirestoreInternal (10.22.0)
Installing FirebaseFunctions (10.22.0)
Installing FirebaseInstallations (10.22.0)
Installing FirebaseMessaging (10.22.0)
Installing FirebaseMessagingInterop (10.22.0)
Installing FirebasePerformance (10.22.0)
Installing FirebaseRemoteConfig (10.22.0)
Installing FirebaseSessions (10.22.0)
Installing FirebaseSharedSwift (10.22.0)
Installing FirebaseStorage (10.22.0)
Installing Flutter (1.0.0)
Installing GTMAppAuth (1.3.1)
Installing GTMSessionFetcher (2.3.0)
Installing GoogleAppMeasurement (10.22.0)
Installing GoogleDataTransport (9.4.1)
Installing GoogleSignIn (6.2.4)
Installing GoogleUtilities (7.13.0)
Installing OrderedSet (5.0.0)
Installing PromisesObjC (2.4.0)
Installing PromisesSwift (2.4.0)
Installing RecaptchaInterop (100.0.0)
Installing SDWebImage (5.19.0)
Installing SwiftyGif (5.4.4)
Installing abseil (1.20220623.0)
Installing app_settings (5.1.1)
Installing cloud_firestore (4.15.7)
Installing cloud_functions (4.6.7)
Installing file_picker (0.0.1)
Installing firebase_analytics (10.8.8)
Installing firebase_app_check (0.2.1-16)
Installing firebase_auth (4.17.7)
Installing firebase_core (2.26.0)
Installing firebase_dynamic_links (5.4.16)
Installing firebase_messaging (14.7.18)
Installing firebase_performance (0.9.3-16)
Installing firebase_remote_config (4.3.16)
Installing firebase_storage (11.6.8)
Installing flutter_inappwebview (0.0.1)
Installing flutter_keyboard_visibility (0.0.1)
Installing flutter_secure_storage (6.0.0)
Installing gRPC-C++ (1.49.1)
Installing gRPC-Core (1.49.1)
Installing geolocator_apple (1.2.0)
Installing google_sign_in_ios (0.0.1)
Installing image_picker_ios (0.0.1)
Installing in_app_review (0.2.0)
Installing leveldb-library (1.22.4)
Installing map_launcher (0.0.1)
Installing nanopb (2.30909.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing permission_handler_apple (9.1.1)
Installing share_plus (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite (0.0.2)
Installing url_launcher_ios (0.0.1)
Installing video_player_avfoundation (0.0.1)
Installing wakelock_plus (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 34 dependencies from the Podfile and 77 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Running pod install...                                             17,5s
Running Xcode build...                                          
Xcode build done.                                           342,1s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Syncing files to device iPhone SE (3rd generation)...           

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: "assets/images/__7.png".
Exception: Asset not found

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:365:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:754:16)
<asynchronous suspension>
#2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:985:3)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name: "assets/images/__7.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a741f(), name: "assets/images/__7.png",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

Syncing files to device iPhone SE (3rd generation)...              227ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone SE (3rd generation) is available at: http://127.0.0.1:51823/aAEXoAwM5uY=/
The Flutter DevTools debugger and profiler on iPhone SE (3rd generation) is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51823/aAEXoAwM5uY=/
Another exception was thrown: Unable to load asset: "assets/images/white_918268.png".
` 
<img width="399" alt="Снимок экрана 2024-03-18 в 00 57 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/143803526/10eb1017-3f73-4c07-b4de-1f96e6de7c8f">

**Comment by sbis04** [comment]
Cocoapods issues are always tricky to solve, glad that you were at least able to solve the issue for now and get the app running through Local Run.

1. Hot Reload and Hot Restart both do a code export before actually applying the changes. So, it might be taking some time before hot reload actually shows up on the device logs and applies to the device.

2. We'll investigate the issue with assets not being exported. In the meantime, can you try deleting the locally exported project once and try running it from the Local Run again? You can open the folder where the project is exported using the following command:

```sh
open ~/Library/Application\ Support/io.flutterflow.prod.mac/
```

**Comment by sbis04** [comment]
Since the actual issue is already resolved, I'm closing this. @JustUserHere can you please create a separate issue for the "assets not exporting" issue? Just to make it easier for us to track, thank you!
