### ISSUE TITLE
WebView Not Working in FlutterFlow

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#2539]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Getting the Below Error Even when google or Flutter Website is opened so no issue with website but with webview. Below is the Error Stack

Uncaught (in promise) Error: LateInitializationError: Field 'connector' has not been initialized.
    at Object.throw\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_ \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[as throw\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (dart_sdk.js:11914:11)
    at get connector (web.dart:17:20)
    at flutter_flow_web_view.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_FlutterFlowWebViewState.new. (flutter_flow_web_view.dart:55:25)
    at Generator.next ()
    at runBody (dart_sdk.js:49741:34)
    at Object.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_async \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[as async\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (dart_sdk.js:49777:7)
    at flutter_flow_web_view.dart:54:28
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_callOnWebViewCreatedCallback\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (web.dart:290:30)
    at web$.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_WebViewXState.new.initState (web.dart:170:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5611:55)
    at framework.StatefulElement.new.mount (framework.dart:5456:5)
    at framework.StatefulElement.new.inflateWidget (framework.dart:4335:15)
    at framework.StatefulElement.new.updateChild (framework.dart:3846:18)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5462:5)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5634:11)
    at framework.StatefulElement.new.mount (framework.dart:5456:5)
    at framework.InheritedElement.new.inflateWidget (framework.dart:4335:15)
    at framework.InheritedElement.new.updateChild (framework.dart:3846:18)
    at framework.InheritedElement.new.performRebuild (framework.dart:5505:16)
    at framework.InheritedElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5462:5)
    at framework.InheritedElement.new.mount (framework.dart:5456:5)
    at framework.StatelessElement.new.inflateWidget (framework.dart:4335:15)
    at framework.StatelessElement.new.updateChild (framework.dart:3846:18)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5462:5)
    at framework.StatelessElement.new.mount (framework.dart:5456:5)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (framework.dart:4335:15)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3846:18)
    at framework.SingleChildRenderObjectElement.new.mount (framework.dart:6758:14)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (framework.dart:4335:15)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3846:18)
    at framework.SingleChildRenderObjectElement.new.mount (framework.dart:6758:14)
    at framework.StatelessElement.new.inflateWidget (framework.dart:4335:15)
    at framework.StatelessElement.new.updateChild (framework.dart:3846:18)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5462:5)
    at framework.StatelessElement.new.mount (framework.dart:5456:5)
    at ParentDataElement.new.inflateWidget (framework.dart:4335:15)
    at ParentDataElement.new.updateChild (framework.dart:3846:18)
    at ParentDataElement.new.performRebuild (framework.dart:5505:16)
    at ParentDataElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_firstBuild\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (framework.dart:5462:5)
    at ParentDataElement.new.mount (framework.dart:5456:5)
    at framework.MultiChildRenderObjectElement.new.inflateWidget (framework.dart:4335:15)
    at framework.MultiChildRenderObjectElement.new.inflateWidget (framework.dart:6893:36)
    at framework.MultiChildRenderObjectElement.new.updateChild (framework.dart:3846:18)
    at framework.MultiChildRenderObjectElement.new.updateChildren (framework.dart:4033:32)
    at framework.MultiChildRenderObjectElement.new.update (framework.dart:6918:17)
    at InheritedModelElement.new.updateChild (framework.dart:3824:14)
    at InheritedModelElement.new.performRebuild (framework.dart:5505:16)
    at InheritedModelElement.new.rebuild (framework.dart:5196:7)
    at InheritedModelElement.new.update (framework.dart:5809:5)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.SingleChildRenderObjectElement.new.update (framework.dart:6765:14)
    at framework.StatelessElement.new.updateChild (framework.dart:3824:14)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at framework.StatelessElement.new.update (framework.dart:5556:5)
    at framework.StatelessElement.new.updateChild (framework.dart:3824:14)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at framework.StatelessElement.new.update (framework.dart:5556:5)
    at framework.StatelessElement.new.updateChild (framework.dart:3824:14)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at framework.StatelessElement.new.update (framework.dart:5556:5)
    at InheritedModelElement.new.updateChild (framework.dart:3824:14)
    at InheritedModelElement.new.performRebuild (framework.dart:5505:16)
    at InheritedModelElement.new.rebuild (framework.dart:5196:7)
    at InheritedModelElement.new.update (framework.dart:5809:5)
    at ParentDataElement.new.updateChild (framework.dart:3824:14)
    at ParentDataElement.new.performRebuild (framework.dart:5505:16)
    at ParentDataElement.new.rebuild (framework.dart:5196:7)
    at ParentDataElement.new.update (framework.dart:5809:5)
    at framework.MultiChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.MultiChildRenderObjectElement.new.updateChildren (framework.dart:3973:32)
    at framework.MultiChildRenderObjectElement.new.update (framework.dart:6918:17)
    at framework.InheritedElement.new.updateChild (framework.dart:3824:14)
    at framework.InheritedElement.new.performRebuild (framework.dart:5505:16)
    at framework.InheritedElement.new.rebuild (framework.dart:5196:7)
    at framework.InheritedElement.new.update (framework.dart:5809:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.InheritedElement.new.updateChild (framework.dart:3824:14)
    at framework.InheritedElement.new.performRebuild (framework.dart:5505:16)
    at framework.InheritedElement.new.rebuild (framework.dart:5196:7)
    at framework.InheritedElement.new.update (framework.dart:5809:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.SingleChildRenderObjectElement.new.update (framework.dart:6765:14)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.updateChild (framework.dart:3824:14)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.performRebuild (framework.dart:5505:16)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.update (framework.dart:5809:5)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.SingleChildRenderObjectElement.new.update (framework.dart:6765:14)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.InheritedElement.new.updateChild (framework.dart:3824:14)
    at framework.InheritedElement.new.performRebuild (framework.dart:5505:16)
    at framework.InheritedElement.new.rebuild (framework.dart:5196:7)
    at framework.InheritedElement.new.update (framework.dart:5809:5)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.updateChild (framework.dart:3824:14)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.performRebuild (framework.dart:5505:16)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.update (framework.dart:5809:5)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.updateChild (framework.dart:3824:14)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.performRebuild (framework.dart:5505:16)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.rebuild (framework.dart:5196:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_NotificationElement.new.update (framework.dart:5809:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.InheritedElement.new.updateChild (framework.dart:3824:14)
    at framework.InheritedElement.new.performRebuild (framework.dart:5505:16)
    at framework.InheritedElement.new.rebuild (framework.dart:5196:7)
    at framework.InheritedElement.new.update (framework.dart:5809:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.SingleChildRenderObjectElement.new.update (framework.dart:6765:14)
    at framework.SingleChildRenderObjectElement.new.updateChild (framework.dart:3824:14)
    at framework.SingleChildRenderObjectElement.new.update (framework.dart:6765:14)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.StatefulElement.new.update (framework.dart:5666:5)
    at framework.StatelessElement.new.updateChild (framework.dart:3824:14)
    at framework.StatelessElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatelessElement.new.rebuild (framework.dart:5196:7)
    at framework.StatelessElement.new.update (framework.dart:5556:5)
    at framework.StatefulElement.new.updateChild (framework.dart:3824:14)
    at framework.StatefulElement.new.performRebuild (framework.dart:5505:16)
    at framework.StatefulElement.new.performRebuild (framework.dart:5643:11)
    at framework.StatefulElement.new.rebuild (framework.dart:5196:7)
    at framework.BuildOwner.new.buildScope (framework.dart:2904:18)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (binding.dart:989:9)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_handlePersistentFrameCallback\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (binding.dart:448:5)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_invokeFrameCallback\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (binding.dart:1386:7)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (binding.dart:1311:9)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_handleDrawFrame\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] (binding.dart:1169:5)
    at Object.invoke (dart_sdk.js:211823:7)
    at \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_engine.EnginePlatformDispatcher.new.invokeOnDrawFrame (dart_sdk.js:183647:15)
    at dart_sdk.js:211594:57
    at Object.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_checkAndCall (dart_sdk.js:12169:16)
    at Object.dcall (dart_sdk.js:12174:17)
    at ret (dart_sdk.js:71929:21)

### Expected Behavior

It should Display the website

### Steps to Reproduce

Create A Page
Add a webView
Put a url init

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CiMjfsIh2rscA0a6Jd/panjwRQ0x6RYEwm8BuaxIjJ5PPCOwQZvv7ak5oO73hSnxIJGGZhj0J/PfqkuztN8c3GwmZbYRxzpF6EQ/gfz6tVYitC86BfW1SBdxTIEye1MOw2whCBNp0S1IF2FOpfuysSXLUNYD3DlgzNeWlKdeK2SrDX1iXc2URm05KZDPz

### Context

One of my important feature has been block so long becuase of it

### Visual documentation

No

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1 & 4.1.33
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by Mdmuzammil16** [comment]
Already Fixed
