### ISSUE TITLE
Can't insert Supabase Row with timestamp field from "Current Time" Global Property

### ISSUE THREAD

**Issue by Mktotoy** [FlutterFlow/flutterflow-issues#316]
## Expected behavior (required)

I would insert to Supabase DB a row with a Timestamp from FF App

## Current behavior (required)

An error occurs when clicking the button who active the action of insert Row to DB : 
dart_sdk.js:5241 Uncaught (in promise) Error: Converting object to an encodable object failed: Instance of 'DateTime'

## To Reproduce (required)

1. Create table with a (exemple) "start_at" timestamp field
2. Set RCS policies to allow all from anon key to the table
3. Connect Supabase to project
4. Create a button "Insert to supabase"
5. Add field "start_at" to action of insert and set value to "Current Time" from global properties
7. Click Run
8. Project run
9. On click insert, have the error 

Error : 
Uncaught (in promise) Error: Converting object to an encodable object failed: Instance of 'DateTime'
    at Object.throw_ [as throw] (dart_sdk.js:5241:11)
    at convert._JsonStringStringifier.new.writeObject (dart_sdk.js:49099:21)
    at convert._JsonStringStringifier.new.writeMap (dart_sdk.js:49172:14)
    at convert._JsonStringStringifier.new.writeJsonValue (dart_sdk.js:49130:28)
    at convert._JsonStringStringifier.new.writeObject (dart_sdk.js:49088:16)
    at _JsonStringStringifier.printOn (dart_sdk.js:49360:19)
    at _JsonStringStringifier.stringify (dart_sdk.js:49350:38)
    at JsonEncoder.convert (dart_sdk.js:48727:45)
    at JsonCodec.encode (dart_sdk.js:48664:52)
    at Object.jsonEncode (dart_sdk.js:51134:25)
    at PostgrestTransformBuilder.new._execute (postgrest_builder.dart:162:23)
    at _execute.next (<anonymous>)
    at runBody (dart_sdk.js:40595:34)
    at Object._async [as async] (dart_sdk.js:40626:7)
    at [_execute] (postgrest_builder.dart:127:37)
    at PostgrestTransformBuilder.new.then (postgrest_builder.dart:400:30)
    at then.next (<anonymous>)
    at runBody (dart_sdk.js:40595:34)
    at Object._async [as async] (dart_sdk.js:40626:7)
    at PostgrestTransformBuilder.new.then (postgrest_builder.dart:384:20)
    at inscriptions_collectes.InscriptionsCollectesTable.new.insert (table.dart:35:14)
    at home_page_widget._HomePageWidgetState.new.<anonymous> (home_page_widget.dart:105:58)
    at Generator.next (<anonymous>)
    at runBody (dart_sdk.js:40595:34)
    at Object._async [as async] (dart_sdk.js:40626:7)
    at home_page_widget.dart:104:32
    at flutter_flow_widgets._FFButtonWidgetState.new.<anonymous> (flutter_flow_widgets.dart:93:32)
    at Generator.next (<anonymous>)
    at runBody (dart_sdk.js:40595:34)
    at Object._async [as async] (dart_sdk.js:40626:7)
    at flutter_flow_widgets.dart:87:15
    at ink_well._InkResponseState.new.handleTap (ink_well.dart:1072:21)
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:253:24)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:627:11)
    at [_checkUp] (tap.dart:306:5)
    at tap.TapGestureRecognizer.new.acceptGesture (tap.dart:276:7)
    at arena.GestureArenaManager.new.sweep (arena.dart:163:12)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:464:20)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:440:14)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:337:11)
    at [_handlePointerEventImmediately] (binding.dart:395:7)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:357:5)
    at [_flushPointerEventQueue] (binding.dart:314:7)
    at [_handlePointerDataPacket] (binding.dart:295:7)
    at Object.invoke1 (dart_sdk.js:196997:7)
    at _engine.EnginePlatformDispatcher.new.invokeOnPointerDataPacket (dart_sdk.js:172337:15)
    at [_onPointerData] (dart_sdk.js:173315:49)
    at dart_sdk.js:173840:30
    at dart_sdk.js:173783:9
    at loggedHandler (dart_sdk.js:173488:11)
    at dart_sdk.js:173406:91
    at Object._checkAndCall (dart_sdk.js:5438:16)
    at Object.dcall (dart_sdk.js:5443:17)
    at ret (dart_sdk.js:62137:21)

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/11921259/210393943-93d34d8b-4839-4257-82fe-fcd49c95c406.png)
![image (1)](https://user-images.githubusercontent.com/11921259/210393953-a6f5e4ad-fda9-4bee-8a5d-f8efb0bfab23.png)

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Web Chrome
* Browser name and version: Version 108.0.5359.125 (Build officiel) (64 bits)
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment]
Hi Mktotoy, 

#I can reproduce this issue and get an exception "Converting object to an encodable object failed: Instance of 'DateTime'" during runtime. It is a bug. Thanks for reporting. It seems to be the same as #297

**Comment by Mktotoy** [comment]
It's the same yes i close this one
