### ISSUE TITLE
Uncaught Invalid argument on developer console during project loading

### ISSUE THREAD

**Issue by reghta** [FlutterFlow/flutterflow-issues#3603]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a project is loaded on Test mode, it throws an error in the Developer Console: 

Uncaught Invalid argument (index): "type"
    at Object.v (https://app.flutterflow.io/main.dart.js:3957:19)
    at bjE.j (https://app.flutterflow.io/main.dart.js:179248:39)
    at Object.G (https://app.flutterflow.io/main.dart.js:190:16)
    at hLF.$1 (https://app.flutterflow.io/main.dart.js:392490:10)
    at fQp.$0 (https://app.flutterflow.io/main.dart.js:181476:20)
    at Object.kRx (https://app.flutterflow.io/main.dart.js:5642:12)
    at fQs.$1 (https://app.flutterflow.io/main.dart.js:181473:9)
    at hVl.$1 (https://app.flutterflow.io/main.dart.js:187784:21)

### Expected Behavior

No error to be thrown for project loading

### Steps to Reproduce

1- Create a new project
2- Tap Test 
3- Open Developer Console
4- Observe the error being thrown during project loading

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89goflf16rbK+5qhQAkKUg4WLg7m9cbEEkYfa7kE5k2Oer+VFJpTdOdY29AJVaYgjoF/vzRjeLPKfI7HxSBUoNowpBuWgGXYGCgb7ahCpGCSHFtHe9UGFSk57SSkRZCJu1pWllgw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![Screenshot 2024-08-11 at 10 56 56 AM](https://github.com/user-attachments/assets/2017e1ef-53db-42f7-a73b-ec0795c584bb)

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

### Additional Information

I thought there is an issue with my project and have been trying to remove various bits to see what has caused the issue. Later after not being able to find the root cause I started a fresh project and realized the error is thrown there too.

Note this does not prevent the project from loading but it leads to confusion and might help find a bug with other implications

**Comment by msusviela** [comment]
Hi @reghta. Thanks for your report. I'll send it to ENG so they can work on this!
