### ISSUE TITLE
Upload data bottom sheet picker doesn't work with custom font

### ISSUE THREAD

**Issue by henrroga** [FlutterFlow/flutterflow-issues#4244]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a custom uploaded font for the upload data / media bottom sheet picker, the gray screen shows up and the error suggests that the project tries to find the font in the Google Fonts package:
```
flutter: Exception: No font family by name '[font_name_retracted]' was found.
flutter: #0      GoogleFonts.getFont (package:google_fonts/google_fonts.dart:3319)
flutter: #1      selectMediaWithSourceBottomSheet.<anonymous closure> (package:[project_name_retracted]/flutter_flow/upload_data.dart:92)
```

### Expected Behavior

The bottom sheet should show and the options should render the correct font.

### Steps to Reproduce

1. Upload a custom font to your project
2. Trigger an action in a button that uploads media
3. Change the Source Picker style font to a custom font

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiPHqw4VOxLhY0ZDfbcBahSc7Q3p9TL03pu0bFEggGLbrBIYMafSkN1RoZOmlTAhXKEWLjmUf3PzXuN7mGu05FzStG5RCwbl+Vw7MITi/aoSrEpGedWt8IJ9NGBTC0aSJnxVSHM9aLlIM2kz3HPK9aDPbNOb7Zwh9f6PHaOI=

### Visual documentation

![IMG_4291](https://github.com/user-attachments/assets/f072e9f4-df25-4de9-8df3-01097cdebd6e)

### Environment

```markdown
- FlutterFlow version: v5.0.6+ released October 18, 2024
- Platform: Web
- Browser name and version: Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.1.1 (23B81)
```

**Comment by paulperez-dev** [comment]
Hi @henrroga,

I was able to reproduce the issue and will forward it to the engineering team for further investigation.
