### ISSUE TITLE
Unable to Use Cache in Backend Queries

### ISSUE THREAD

**Issue by carlosmachina** [FlutterFlow/flutterflow-issues#4788]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using project dependencies, FlutterFlow is unable to work with caching.
This was tested on a blank project, importing the same library.
The library and API call work correctly without Caching.

## Device Logs (EDGE):

```
Launching lib\main.dart on Edge in debug mode…
Waiting for connection from debug service on Edge…            
lib/pages/home_page/home_page_model.dart:27:10: Error: Type 'ApiCallResponse' not found.
  Future<ApiCallResponse> dischargeFilters({
         ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:30:21: Error: Type 'ApiCallResponse' not found.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:26:57: Error: 'ApiCallResponse' isn't a type.
  final _dischargeFiltersManager = FutureRequestManager<ApiCallResponse>();
                                                        ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:30:21: Error: 'ApiCallResponse' isn't a type.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///%AppData%/FlutterFlow/flutterflow/a_p_i_cache_test_project/lib/pages/home_page/home_page_model.dart, which contains the type: InvalidType(<invalid>).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3224)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3185)
#2      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      InstantiatorGeneratorVisitor.splayNodes (package:dev_compiler/src/js_ast/template.dart:224)
#6      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:604)
#7      Template.instantiate (package:dev_compiler/src/js_ast/template.dart:118)
#8      JsBuilder.call (package:dev_compiler/src/js_ast/builder.dart:212)
#9      ProgramCompiler._emitGenericClassType (package:dev_compiler/src/kernel/compiler.dart:3236)
#10     ProgramCompiler._emitClassRef (package:dev_compiler/src/kernel/compiler.dart:3218)
#11     ProgramCompiler._emitConstructorName (package:dev_compiler/src/kernel/compiler.dart:3252)
#12     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:6519)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:6666)
#14     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3925)
#15     ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compiler.dart:1932)
#16     ProgramCompiler._initializeFields.emitFieldInit (package:dev_compiler/src/kernel/compiler.dart:1889)
#17     ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1905)
#18     ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1747)
#19     ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1712)
#20     ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3621)
#21     ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1711)
#22     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2553)
#23     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3610)
#24     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1709)
#25     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:1374)
#26     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:896)
#27     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#28     List.forEach (dart:core-patch/growable_array.dart:417)
#29     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#30     List.forEach (dart:core-patch/growable_array.dart:417)
#31     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#32     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:221)
#33     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:870)
<asynchronous suspension>
#34     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:685)
<asynchronous suspension>
#35     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1385)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Edge…               17,4s
Failed to compile application.
```

## Device Logs (Chrome)

```
Launching lib\main.dart on Chrome in debug mode…
Waiting for connection from debug service on Chrome…          
lib/pages/home_page/home_page_model.dart:27:10: Error: Type 'ApiCallResponse' not found.
  Future<ApiCallResponse> dischargeFilters({
         ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:30:21: Error: Type 'ApiCallResponse' not found.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:26:57: Error: 'ApiCallResponse' isn't a type.
  final _dischargeFiltersManager = FutureRequestManager<ApiCallResponse>();
                                                        ^^^^^^^^^^^^^^^
lib/pages/home_page/home_page_model.dart:30:21: Error: 'ApiCallResponse' isn't a type.
    required Future<ApiCallResponse> Function() requestFn,
                    ^^^^^^^^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///%AppData%/FlutterFlow/flutterflow/a_p_i_cache_test_project/lib/pages/home_page/home_page_model.dart, which contains the type: InvalidType(<invalid>).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3224)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3185)
#2      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      InstantiatorGeneratorVisitor.splayNodes (package:dev_compiler/src/js_ast/template.dart:224)
#6      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:604)
#7      Template.instantiate (package:dev_compiler/src/js_ast/template.dart:118)
#8      JsBuilder.call (package:dev_compiler/src/js_ast/builder.dart:212)
#9      ProgramCompiler._emitGenericClassType (package:dev_compiler/src/kernel/compiler.dart:3236)
#10     ProgramCompiler._emitClassRef (package:dev_compiler/src/kernel/compiler.dart:3218)
#11     ProgramCompiler._emitConstructorName (package:dev_compiler/src/kernel/compiler.dart:3252)
#12     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:6519)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:6666)
#14     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3925)
#15     ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compiler.dart:1932)
#16     ProgramCompiler._initializeFields.emitFieldInit (package:dev_compiler/src/kernel/compiler.dart:1889)
#17     ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1905)
#18     ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1747)
#19     ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1712)
#20     ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3621)
#21     ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1711)
#22     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2553)
#23     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3610)
#24     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1709)
#25     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:1374)
#26     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:896)
#27     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#28     List.forEach (dart:core-patch/growable_array.dart:417)
#29     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#30     List.forEach (dart:core-patch/growable_array.dart:417)
#31     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#32     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:221)
#33     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:870)
<asynchronous suspension>
#34     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:685)
<asynchronous suspension>
#35     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1385)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome…          Failed to compile application.
   17,4s
```

> [!note]
> The `%AppData%` shortcut was added by me for privacy reasons, in the original logs, it showed the full path to the folder.

## The API Call

![image](https://github.com/user-attachments/assets/47f2df48-c184-42f6-86a4-e0f1cb61508a)

![image](https://github.com/user-attachments/assets/b1ea6496-f3f8-4a1e-88a4-9ecbaaebdfae)

## The Data Structure

![image](https://github.com/user-attachments/assets/12c8ef86-ea20-42e2-a68e-67c896f80049)

![image](https://github.com/user-attachments/assets/b3019baa-fe56-4cca-825e-d24dfa28f398)

### Expected Behavior

To be able to use the **Cache** function on a **Backend Query** and build the project.
Also, that FlutterFlow correctly store the retreived data in the **Cache**.

### Steps to Reproduce

1. Create a Library Project
2. Create an API request in the library
3. Create a Custom Data Type with nested data types
4. Retrieve the API response as the Custom Data Type
5. Create a Project
6. Add the Library as a Dependency
7. Use the API call as a BackendQuery anywhere
8. Set the BackendQuery to enable Cache
9. Run a local test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fl+fqyItNpbxa7ar2dvlR/WAvKUR/RY0/m+0bURQgfIvqE4kUeMnOVFdJYsOGdwlIJFmj8XgK0qHRkfz2G8ECIUuteYNe1c1uFj3zcFiVMJi2ErqdPkBTM/xjfEzAyMG4mA9TOu9oSVIO6mGuBtmRVizdJZDoOUgzNeabLr/OpFaWFh3dIDhVwmNecCfn

### Visual documentation

The visual documentation is included in the body of text of this ticket.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.9+ released October 25, 2024
- Platform: Web
- Browser name and version: Microsoft Edge Version 130.0.2849.56 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Version 24H2 (OS Build 26100.2161)
```

### Additional Information

This problem started while trying to use the cache to avoid a Timer from hitting our API every second.
We need a timer in seconds that gets its initial value from the Backend Query. Without caching, there's no way to avoid this timer to excessively hit our Backend, making it impeditive for production.

**Comment by Alezanello** [comment]
Thank you so much for bringing this to our attention! I was able to confirm the bug on my end as well, so I’ll pass this along to the engineering team for further review.

We appreciate your help!
