### ISSUE TITLE
TextField with Initial Value set by Custom Function throws error in Debug Mode

### ISSUE THREAD

**Issue by dustinkerstein** [FlutterFlow/flutterflow-issues#5010]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting the Initial Value of a TextField to a Custom Function with the following code:

```
String? concatStringsLineBreak(
  String? s1,
  String? s2,
) {
  return '${s1 ?? ''}\n${s2 ?? ''}';
}
```

A dependOnInheritedWidgetOfExactType LocalizationScope error is returned in the UI (see attached photo) when the app is run in Debug mode. 

### Expected Behavior

No error should be thrown. Note that Run mode works as expected. The issue can only be replicated in Debug builds.

### Steps to Reproduce

1. Create TextField with Initial Value set by Custom Function (see code above)
2. Set `s1` string to `relative` format and `s2` to custom format of `M/d/yy h:mm a`
3. Run app in debug mode and note error when viewing this TextField
4. Run app in release mode and note there is no error and TextField renders as expected 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiMjfsItPvt9K+KrcYcFF+CcRM0McX5Ir1utsewgjGKL1Bu02Ys/7NxFoXsylaVNfeFD/pHsewfPHk+HuV8FdGEiYfrZg/5BXVQvee2iQb4yICrrhe39tO/tTIGqd5MKjnCJ4ANJaR04B12CULu6WcHPDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="720" alt="image" src="https://github.com/user-attachments/assets/80f680e2-4cd6-4ec9-986f-354f5e451609">
<img height="720" alt="image" src="https://github.com/user-attachments/assets/783f0ca1-cc65-40a5-b081-220a728385fb">

### Environment

```markdown
- FlutterFlow version: 5.0.14 
- Platform: MacOS build and running on Samsung Fold 4
- Operating system and version affected: Android 14
```

**Comment by paulperez-dev** [comment]
Hi @dustinkerstein,

Thank you for reporting this! I tried to reproduce the issue, but wasn’t able to replicate it on my end. Could you please confirm the version you are using? Also, is the user able to edit the value in the TextField?

Looking forward to your response so we can assist further!

**Comment by dustinkerstein** [comment]
Hi @paulperez-dev, I'm able to replicate it using a fresh blank page with a single TextField, regardless of ReadOnly. The important step seems to be using a DateTime formatter (doesn't seem to matter which) before passing this parameter into the custom function noted in the first post.

<img width="926" alt="image" src="https://github.com/user-attachments/assets/50c83eb5-8653-4d7c-8997-e12572bd6d4a">

Here's a bug report code for this new widget: ITFTiMjfsItPvt9K+KrcYcFF+CcRM0McX5Ir1utsewgjGKL1BqQMeMjBYktBTem6aVNfMFeIpDkCwfCOiIXhMPJfFwedRYs7yJNIUBbOe2iQb4yICrrhe39tO/tTIGqd5MKjnCJ4ANJaR04B12CULu6WcHPDFOu/Zwh9f6PHaOI=

I'm running the MacOS FlutterFlow app version 5.0.14 and testing in debug mode on an Android 14 device.

Let me know if you're still unable to replicate or if there's anything else I can get you. Thanks!

**Comment by paulperez-dev** [comment]
I’m still unable to replicate the issue on my end.

Here’s the configuration I’m using in this project: [Project Link](https://app.flutterflow.io/project/qa-3167-emxeam).

If the issue persists on your side, it might be something specific to your project. In that case, reaching out to FlutterFlow support at **support@flutterflow.io** would be the best way to resolve it. 

I'm closing this issue.

As a side note, if you don’t require input from the end user, you might consider using a Text widget to display labels in the app for better efficiency.

**Comment by dustinkerstein** [comment]
I'm a little hesitent to change the language settings on my project, but if you don't mind messing with your test project, you may want to try with setting the languages to English. Here is what your settings look like:

<img width="813" alt="image" src="https://github.com/user-attachments/assets/3c2363c7-861a-42ae-851d-90d2d3d14700">

And mine: 
<img width="813" alt="image" src="https://github.com/user-attachments/assets/c16d9a52-0483-4820-8828-9e4bae2060e9">

Given the error mentions `LocalizationScope` I'm feeling it could be something related to languages, but that's just a guess.

**Comment by paulperez-dev** [comment]
Hi @dustinkerstein!

I will add the language configuration. There’s no need for you to adjust your project configuration at this point. I’ll proceed with testing and will let you know if anything new comes up.

If there’s another configuration needed to replicate the issue, feel free to share it, and I’ll make the necessary changes.

**Comment by paulperez-dev** [comment]
Hi @dustinkerstein!

Thank you for your report. After adding the language, I was able to replicate the issue. I’ll escalate this to the engineering team so they can work on a fix.

Thank you for bringing this to our attention!

**Comment by RikHaanen** [comment]
Thanks for the info, I seem to have the same issue (so I am not creasy, although I was on my way getting there ;)

**Comment by digitino** [comment]
I'm still experiencing this issue. Is this planned to be fixed in any new release soon?

**Comment by vdevc** [comment]
I am also experiencing this problem. At the beginning I thought it was related to dropdown and translations of content. I described it [here](https://community.flutterflow.io/ask-the-community/post/strange-error-on-generated-code-BEyubCA6ALKEpYF), but now I am getting it also in another contest where i form text field is used.

here is the stack trace

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder:
dependOnInheritedWidgetOfExactType<_LocalizationsScope>() or dependOnInheritedElement() was called
before _ProgramDetailsGeneralWidgetState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively,
initialization based on inherited widgets can be placed in the didChangeDependencies method, which
is called after initState and whenever the dependencies change thereafter.

The relevant error-causing widget was:
  Navigator-[LabeledGlobalKey<NavigatorState>#4f343]
  Navigator:file:///Users/vincenzo/.pub-cache/hosted/pub.dev/go_router-12.1.3/lib/src/builder.dart:316:30

When the exception was thrown, this was the stack:
#0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5864:9)
#1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:5907:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4922:14)
#3      Localizations.of (package:flutter/src/widgets/localizations.dart:536:48)
#4      FFLocalizations.of (package:fidelity/flutter_flow/internationalization.dart:14:21)
#5      _ProgramDetailsGeneralWidgetState.initState (package:fidelity/pages/program/program_details_general/program_details_general_widget.dart:158:29)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5762:55)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607:5)
...     Normal element mounting (24 frames)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480:16)
#32     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049:36)
#33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061:32)
...     Normal element mounting (188 frames)
#221    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480:16)
#222    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049:36)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#224    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#225    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7074:17)
#226    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#228    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#230    StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#234    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#238    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#239    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:112:11)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#242    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#244    StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#248    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#249    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:112:11)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#252    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#253    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#254    StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#257    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#258    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#259    StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#261    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6921:14)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#263    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6921:14)
#264    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#266    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#267    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#268    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#269    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#270    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#271    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#274    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#276    StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#277    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#280    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#284    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#285    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:112:11)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#289    StatelessElement.update (package:flutter/src/widgets/framework.dart:5707:5)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#292    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#293    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#296    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#297    StatelessElement.update (package:flutter/src/widgets/framework.dart:5707:5)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#299    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#300    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#301    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#303    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#304    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#305    ProxyElement.update (package:flutter/src/widgets/framework.dart:5960:5)
#306    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#307    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#308    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#309    Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#310    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#311    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2753:11)
#312    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#313    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1176:21)
#314    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#315    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#316    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#317    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#318    _invoke (dart:ui/hooks.dart:312:13)
#319    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
#320    _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

Is there any chance to see this issue resolved?

**Comment by tomkosmita** [comment]
The issue is still here

In my case it has to do the the initial option value of the drop down where labels and values are used.
On some situations the initial option value was set to null.
When I removed all initial states the attached error did disappear.

Any chances to get this resolved?
@paulperez-dev ?



<img width="1278" height="346" alt="Image" src="https://github.com/user-attachments/assets/95d91977-26fa-4fd1-b4ee-f5dfbc8e4159" />
