### ISSUE TITLE
Invalid join on SQLite database asset path on Windows

### ISSUE THREAD

**Issue by MartijnVermeulen96** [FlutterFlow/flutterflow-issues#5204]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the `initializeDatabaseFromDbFile` method in `lib\backend\sqlite\init.dart`, the path for the database is joined using `path`'s `join`.
On Windows, this defaults to using the backslash to join strings. However, Flutter needs to use the forward slash to access assets, like the SQLite DB.

The current error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets\sqlite_db_files\redacted.db".
The asset does not exist or has empty data.
#0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:327:9)
<asynchronous suspension>
#1      initializeDatabaseFromDbFile (package:redacted/backend/sqlite/init.dart:23:26)
<asynchronous suspension>
#2      SQLiteManager.initialize (package:redacted/backend/sqlite/sqlite_manager.dart:24:17)
<asynchronous suspension>
#3      main (package:redacted/main.dart:48:3)
<asynchronous suspension>
```

### Expected Behavior

```
 final databaseData = await rootBundle
        .load(join('assets', 'sqlite_db_files', databaseAssetFilename));
```

Should be replaced by String interpolation for example, giving forward slashes as a result. 
```
final databaseData = await rootBundle
    .load('assets/sqlite_db_files/$databaseAssetFilename');
```

### Steps to Reproduce

1. Create a non-empty SQLite database
2. Enable SQLite in FlutterFlow and add the database as a resource
3. Test on Windows to target platform Windows
4. The application will fail to boot

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NotApplicable

### Visual documentation

![WindowsFFNotBootingUpWithSQLite](https://github.com/user-attachments/assets/d62de5d1-4198-406d-91a0-6eee51191c57)

### Environment

```markdown
FlutterFlow v5.0.18+ released December 26, 2024
Flutter version is 3.24.2
Platform: Windows
Operation system and version: Windows 11 Version 24H2

flutter doctor output:
PS C:\Users\Martijn\AppData\Roaming\FlutterFlow\flutterflow> flutter --version
Flutter 3.24.2 • channel stable • https://github.com/flutter/flutter.git
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.26100.2605], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.5.5)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2024.3)
[√] VS Code (version 1.96.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

**Comment by Alezanello** [comment]
You’re absolutely correct—it seems the team prioritized SQLite functionality for Android and iOS, and not the Windows platform. I’ll escalate this to the engineering team for a closer review and to explore a potential fix, ensuring there’s no need to adjust code between platforms.

Thank you for bringing this to our attention, and we appreciate your patience as we work on this!

**Comment by dholakashyap** [comment]
i too got same error.
