### ISSUE TITLE
Upload File not Working Android 13

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#743]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Files are not uploading on Android 13, working fine on older versions of Android

### Expected Behavior

It should allow the user to select a file to upload

### Steps to Reproduce

1. Create a project and add a file upload action on a button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

IT4OhfLluIhOsdhE17ruYMFVoCoWQ2Y5a7xNm+0aURM3C7HNGu4MPsneVFRuZryqTwhEJk6ZrDo0/PfqiYXxUfddMgWcR5xSycx+aj3LcEWVMpCvBpaRfW1QL+ZbfVfCy5mvuAlAPut0S1pk6k6yAOu9UhfcNrLMClYnRvilLdeK2SrDX1iXc2URm05KZDPz

### Context

it is not allowing users on android 13 to select files

### Visual documentation

It's showing this error when tested locally on android 13 emulator:

`I/flutter ( 4496): [MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
E/flutter ( 4496): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
E/flutter ( 4496): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 4496): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:504:35)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496): #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:93:33)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496): #4      selectFile (package:sample_permission/flutter_flow/upload_data.dart:235:23)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496): #5      _HomePageWidgetState.build.<anonymous closure> (package:sample_permission/pages/home_page/home_page_widget.dart:63:36)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496): #6      _FFButtonWidgetState.build.<anonymous closure> (package:sample_permission/flutter_flow/flutter_flow_widgets.dart:101:19)
E/flutter ( 4496): <asynchronous suspension>
E/flutter ( 4496):`

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.146 
- Operating system and version affected: MacOS Ventura 13.0
```

**Comment by SiraEnterprises** [comment]
+ 1 for this. It works on run mode but doesn't work on app. Doesn't do anything on click of upload button

**Comment by Fredjoha01** [comment]
@SameerShahzad99  Same here. It's been like this since the android update. This should be a priority as it renders many apps functionality useless on MANY devices...

**Comment by bulgariamitko** [comment]
This issue is duplicated - https://github.com/FlutterFlow/flutterflow-issues/issues/680
