### ISSUE TITLE
Unable to authenticate some of my users

### ISSUE THREAD

**Issue by cskonstantyn** [FlutterFlow/flutterflow-issues#903]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This issue happened a few months back and we ignored it. Now it come back for several accounts. 
Users are unable to log in to their accounts. One account was created on April 2 create@mail.ca and another on April 27th creator@mail.ca The issue occurred simultaneously yesterday for 2 accounts. When providing a log in users are not taken to their account and stay on the login pages.  Latest test when registering new account allowed us to log in using test@gmail.ca. 

When trying to register a new account new@mail.ca the user is taken to the register page and later on taken to their home pages. But when logging out and trying to log back in using login, the same error occurs where a user is unable to log in to their account. Currently using google auth.

When testing with f12 the error show as follow:
xpected null value.
    at Object.throw_ [as throw] (dart_sdk.js:5397:11)
    at Object.nullCheck (dart_sdk.js:5718:30)
    at MappedListIterable.new.<anonymous> (schema_util.dart:38:62)
    at MappedListIterable.new.elementAt (dart_sdk.js:24683:25)
    at ListIterator.new.moveNext (dart_sdk.js:24472:55)
    at JsIterator.next (dart_sdk.js:7391:21)
    at List.of (dart_sdk.js:46871:18)
    at MappedListIterable.new.toList (dart_sdk.js:24279:30)
    at Object.getDataList (schema_util.dart:38:61)
    at [_initializeFields] (users_record.dart:178:22)
    at new users_record.UsersRecord.__ (users_record.dart:14:5)
    at UsersRecord.fromSnapshot (users_record.dart:191:77)
    at users_record.dart:189:41
    at _RootZone.runUnary (dart_sdk.js:40524:59)
    at _FutureListener.then.handleValue (dart_sdk.js:35738:29)
    at handleValueCallback (dart_sdk.js:36299:49)
    at _Future._propagateToListeners (dart_sdk.js:36337:17)
    at [_completeWithValue] (dart_sdk.js:36172:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36206:35)
    at Object._microtaskLoop (dart_sdk.js:40821:13)
    at _startMicrotaskLoop (dart_sdk.js:40827:13)
    at dart_sdk.js:36561:9
throw_ @ dart_sdk.js:5397
nullC

### Expected Behavior

We expect users to be able to log in to their accounts and be redirected to the logged-in page after they press login.

### Steps to Reproduce

One way to reproduce:
1. Go to Log In page. 
2. Use any of 3 account (create@mail.ca, creator@mail.ca, new@mail.ca) with a test password. You can use this test password Qweqwert55! to test this issue.

Second way
1. Go to Sign up page
2. Fill up the registration with dummy info
3. get to setting page and log out
4. Try to Log In 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89godRH7rqIKfl6hQIgQ0QnU7gnlO1ucx4dGIvpP5oiZ8zRV0NKTOrjdFZIPmCWpFEezPzshtjhV/cqYBKafoRj0JVPWg3iZHi6V8mRCrWCZH9AAdtUJ3Ki4Z+3sCVBIbJZdEFl31+TNa3qNleeY8aSfxBlZ7vfcPo=

### Context

The issue will affect our app testing and postpone our app launch because we don't want users to register for our app and later on find out they cant log back into their accounts. And we as a company won't even know the reason why they can't log back into their accounts

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121922639/6062e0d3-4056-48b7-94dd-b389bbfe35a0)

### Environment

```markdown
- FlutterFlow version: v3.7.12 (released May 18th, 2023)
- Platform: (Web, Desktop, FlutterFlow Test Mode)
- Browser name and version: Desktop (web) Edge Version 113.0.1774.42, Mobile (web) Edge Version 113.0.1774.36
- Operating system and version affected:
```

**Comment by cskonstantyn** [comment]
Not sure what this status update means? Thanks in advance

**Comment by wenkaifan0720** [comment]
Hi @cskonstantyn. Is this issue still happening to you? I tried with the three accounts you gave and they could all log in now.
